export const courses: Course[] = [
    {
        id: '0',
        name: 'English in 1 month',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid, quibusdam',
        price: 1500,
        isDisabled: false,
        languageLearningId: '0',
        categoryId: '0',
        audienceId: '0',
        imageUrl: 'https://coursecloud.org/wp-content/uploads/2020/11/Complete-English-Course-Intermediate-Level.jpg',
    },
    {
        id: '1',
        name: 'Italian for Students',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid, quibusdam',
        price: 0,
        isDisabled: false,
        languageLearningId: '4',
        categoryId: '2',
        audienceId: '3',
        imageUrl: 'https://www.ed2go.com/common/images/2/23350.jpg',
    },
    {
        id: '2',
        name: 'French for beginners',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid, quibusdam',
        price: 2000,
        isDisabled: false,
        languageLearningId: '2',
        categoryId: '3',
        audienceId: '6',
        imageUrl: 'https://adaminischool.com/wp-content/uploads/2021/03/French-ClassesOnline-WEB.jpg',
    },
    {
        id: '3',
        name: 'Arabic for Students',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid, quibusdam',
        price: 1800,
        isDisabled: false,
        languageLearningId: '7',
        categoryId: '2',
        audienceId: '3',
        imageUrl: 'https://mishkahacademy.com/wp-content/uploads/2022/02/60.jpg.webp',
    },
    {
        id: '4',
        name: 'Korean',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid, quibusdam',
        price: 2200,
        isDisabled: true,
        languageLearningId: '5',
        categoryId: '2',
        audienceId: '2',
        imageUrl: 'https://www.90daykorean.com/wp-content/uploads/2023/12/Online-Korean-Course-min-1.png',
    },
    {
        id: '5',
        name: 'Chinese in 1 month',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid, quibusdam',
        price: 0,
        isDisabled: false,
        languageLearningId: '6',
        categoryId: '3',
        audienceId: '6',
        imageUrl: 'https://thumbs.dreamstime.com/z/chinese-language-typographic-header-school-course-study-foreign-languages-native-speaker-idea-global-communication-vector-231281469.jpg',
    },
    {
        id: '6',
        name: 'Japanese',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid, quibusdam',
        price: 0,
        isDisabled: true,
        languageLearningId: '3',
        categoryId: '2',
        audienceId: '3',
        imageUrl: 'https://www.axiombd.com/wp-content/uploads/2023/06/japanese-language-course.png',
    },
    {
        id: '7',
        name: 'English for All',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid, quibusdam',
        price: 1000,
        isDisabled: false,
        languageLearningId: '0',
        categoryId: '3',
        audienceId: '6',
        imageUrl: 'https://kodakco.sgp1.digitaloceanspaces.com/blog/wp-content/uploads/2024/07/16125413/english-british-england-language.webp',
    },
    {
        id: '8',
        name: 'Persian',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid, quibusdam',
        price: 1900,
        isDisabled: true,
        languageLearningId: '8',
        categoryId: '3',
        audienceId: '0',
        imageUrl: 'https://static.youthop.com/uploads/2019/05/persian-language-summer-course-2019-in-iran-.jpg',
    },
];