export const languages: Language[] = [
    {
        id: '0',
        name: 'English',
        code: 'en',
        slug: 'US',
        isDisabled: false,
    },
    {
        id: '1',
        name: 'Russian',
        code: 'ru',
        slug: 'RU',
        isDisabled: false,
    },
    {
        id: '2',
        name: 'French',
        code: 'fr',
        slug: 'FR',
        isDisabled: false,
    },
    {
        id: '3',
        name: 'Japanese',
        code: 'ja',
        slug: 'JP',
        isDisabled: false,
    },
    {
        id: '4',
        name: 'Italian',
        code: 'it',
        slug: 'IT',
        isDisabled: false,
    },
    {
        id: '5',
        name: 'Korean',
        code: 'ko',
        slug: 'KR',
        isDisabled: false,
    },
    {
        id: '6',
        name: 'Chinese',
        code: 'zh',
        slug: 'CN',
        isDisabled: false,
    },
    {
        id: '7',
        name: 'Arabic',
        code: 'ar',
        slug: 'SA',
        isDisabled: false,
    },
    {
        id: '8',
        name: 'Persian',
        code: 'fa',
        slug: 'IR',
        isDisabled: false,
    },
    {
        id: '9',
        name: 'Hindi',
        code: 'hi',
        slug: 'IN',
        isDisabled: false,
    },
];